### PR TITLE
[WIFI-3150] Add: external databases as optional dependencies for Helm chart

### PR DESCRIPTION
**Pull request by dunaev-opsfleet**

### CODE REVIEW

**Comment by brennerm** [comment]
Looking good but I'm just wondering if it'd be better to put the databases into the assembly chart in case there are other services than the gateway that require a database. 
@dunaev-opsfleet What's your opinion?

Additionally IMO we should set the correct DB URL depending on which DB provider is enabled and only allow one provider to be enabled at most.

**Comment by dunaev-opsfleet** [comment]
@brennerm 
> I'm just wondering if it'd be better to put the databases into the assembly chart in case there are other services than the gateway that require a database.

I don't think it would be good to have DB configuration in assembly as each service could use or NOT use database for their own purposes (say, uCentralGW will use PostgreSQL, uCentralSec will use SQLite and uCentralFMS will use MySQL), so with that we would be able to configure it in values file in the same manner as we have it for now for Zookeeper in Kafka installation - https://github.com/Telecominfraproject/wlan-cloud-ucentral-deploy/blob/main/chart/values.yaml#L35-L47
With the same appoach we will be able to enable/disable external database usage by defining something like this:
```
ucentralgw:
  enabled: true
  configProperties:
    storage.type: postgresql
    # db creds
    ....
  postgresql:
    enabled: true
    fullnameOverride: ucentralgw-postgresql
    # db creds
    ....
```
This way we will have the best flexibility that we want

> Additionally IMO we should set the correct DB URL depending on which DB provider is enabled

Yes, we could do that, but with this we will need to add fullnameOverride in this chart for every provider (which is OK by me) and credentials that will be used, so we would be sure what service name we will have and what credentials it will use out-of-box

> and only allow one provider to be enabled at most.

Hm... Not sure how we could do that. Maybe you have experience with setting up such logic?

**Comment by leonidlm** [comment]
@dunaev-opsfleet although in "pure" microservice design, each service should have its own database, in reality (unfortunately) we can't say that a specific DB is used only by one service - we'll probably have one DB shared by a few services, the same way as Kafka now is used and connected to by a few services in the system.

Saying the above, we must move the DB configuration to the assembly chart as Max suggested. Also, as he mentioned in his comments, we should set the proper DB_URL.

If you want to make sure we are doing the correct move, I would suggest asking Stephane what are the plans for the external DB storage to verify our design matches the architecture.

**Comment by dunaev-opsfleet** [comment]
@leonidlm 
I'm not sure about that based on the current state of the application - it seems that every application has it's own SQLite database with it's own name, so it should not correlate
If we are going to go with one shared DB cluster per uCentral environment we would need to find a way to create additional database in the shared instance which will probably be kinda painful as it will require us to have some kind init script for every database type, so instance per database is the way to go in the same manner as we have it now with SQLite databases
I'll ask Stephane about plans for shared databases and will get back here
Will change PR state to draft for now

**Comment by dunaev-opsfleet** [comment]
@brennerm @leonidlm Yesterday Stephane gave me more information on how microservices are going to work with external databases:
1. Services may use SQLite if it doesn't have a load (for example, less than 250 APs is considered to be low load)
2. It is expected that the only service that is going to be scaled horizonticaly is uCentralGW, so it is potentially the only service that will really need external DB, but other services will also support it
3. Main focus on external DB implementation is going to be PostgreSQL
4. Every service has it's own database and the will only use its own service, so we can be sure that one service will not make requests to the database of another service (the only way of communication between services is OpenAPI)

Based on that, I'm pretty sure that the approach that I was going to is a best one, since it will give us maximum flexibility, transparency and independence of components

If you approve that, I'll merge the PR and backport it to other services in case uCentral users would like to store service DB in RDS and not SQLite (which I'm sure will be actual)

**Comment by oblom0v** [comment]
Is it possible to achieve both? I mean have the flexibility to choose a separate DB instance per microservice in the microservice specific charts but also have the possiblity to deploy a shared instance used by all microservices in the assembly chart?
IMO a DB instance per microservice sounds like overhead and I am not sure if this would meet production requirements, since I would still manage a database cluster separately with proper high availability and replication configuration. But I think it makes sense to give the user the flexibility to choose the desired storage on a microservice level.
For the initialization of a shared instance: at least the PostgreSQL and MySQL Docker images have a directory where you can put .sh or .sql files for initialization of multiple DBs. Credentials could be passed via environment variables in these scripts.

**Comment by dunaev-opsfleet** [comment]
@oblom0v We could do that, but I'd say that it would overcomplicate the deployment method.
From my point of view, Docker-deployed databases are intended to be deployed in a one-instance - one-database manner (based on https://hub.docker.com/r/bitnami/postgresql and https://hub.docker.com/_/postgres images). If you want to have one DB cluster for multiple databases, it is a good idea to move PostgreSQL to an external service, for example RDS in AWS case as it would allow to have a much stable and fault-tolerant solution than Docker deployment. Especially it's actual in case with AWS spot instances where any HA setup have potential to be down. The only solution is either move DB to on-demand instances OR run sync replication (which can simply kill the whole cluster on any downtime from my experience)

@leonidlm @brennerm What are your thoughts on that? If we want to do the most flexible way that @oblom0v proposed, I could do that, but still from my point of view it doesn't go well with Docker approach

**Comment by dunaev-opsfleet** [comment]
@leonidlm @oblom0v @brennerm 
As I've noted in https://telecominfraproject.atlassian.net/browse/WIFI-3150 , I've tested deployment with external DB using values from https://github.com/Telecominfraproject/wlan-testing/pull/147 and it worked correctly
If everything is correct, please approve this PR so I could merge it

**Review by brennerm — APPROVED** [review]

**Pull request merged**
