### PR TITLE
[WIFI-5775] Run SDK tests on a PR level

### PR DESCRIPTION
**Pull request by oblom0v**
Signed-off-by: Johann Hoffmann <johann.hoffmann@mailbox.org>

### CODE REVIEW

**Comment by oblom0v** [comment]
Requires https://github.com/Telecominfraproject/wlan-testing/pull/282 to be merged first.

**Review by dunaev-opsfleet — APPROVED** [review]

**Comment by brennerm** [comment]
@oblom0v But this is not going to block merging the PR even if the tests fail, right? It'll just trigger a test execution without waiting for the result.

**Comment by oblom0v** [comment]
@brennerm nope it won't block merging. Ideally it should be the PR owner's responsibility to ensure successful CI runs, so don't know if we should enforce that. WDYT?

**Comment by brennerm** [comment]
I'd expect failing tests to prevent a PR from being merged. If the result of the test execution has no effect nobody is going to care.

**Comment by oblom0v** [comment]
yeah probably you're right. I'll clarify that and will then enforce it if everything works as expected.

**Pull request merged**
